spring:
  datasource:
    url: jdbc:h2:mem:database

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:region_data.sql
        - classpath:creator_data.sql

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

# CSV Import 설정
csv:
  import:
    password: ${CSV_IMPORT_PASSWORD:dev_password_123}
  links:
    collection-url: ${CSV_LINKS_COLLECTION_URL}

logging:
  level:
    root: INFO
