spring:
  datasource:
    url: jdbc:h2:mem:database

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:region_data.sql
        - classpath:creator_data.sql

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
